# CONFIGURAÇÃO AZURE SQL
spring.datasource.url=jdbc:sqlserver://servidor-dai-tub.database.windows.net:1433;database=tub_db;user=admin_tub@servidor-dai-tub;password=Tropa.Da.Programacao;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=admin_tub
spring.datasource.password=Tropa.Da.Programacao
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# SPRING JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Mudar a porta para não dar erro de "Port already in use"
server.port=8081